# Generated by Django 3.1.5 on 2021-01-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarksModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rollno', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=125)),
                ('marks_maths', models.IntegerField()),
                ('marks_physics', models.IntegerField()),
                ('marks_chemistry', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
